const char cssString[] = "body {\n"
"  font-family: Helvetica Neue, Arial, sans-serif;\n"
"  text-align: center;\n"
"}\n"
"\n"
".wrapper {\n"
"  max-width: 800px;\n"
"  margin: 50px auto;\n"
"}\n"
"\n"
"h1 {\n"
"  font-weight: 200;\n"
"  font-size: 3em;\n"
"  margin: 0 0 0.1em 0;\n"
"}\n"
"\n"
"h2 {\n"
"  font-weight: 200;\n"
"  font-size: 0.9em;\n"
"  margin: 0 0 50px;\n"
"  color: #999;\n"
"}\n"
"\n"
"a {\n"
"  margin-top: 50px;\n"
"  display: block;\n"
"  color: #3e95cd;\n"
"}\n";
