const char indexString[] = "<!DOCTYPE html>\n" 
"<html>\n"
"  <head>\n"
"    <title>Hacker Lab Aquaponics</title>\n"
"    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"></script>\n"
"    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"wrapper\">\n"
"      <h1>Hacker Lab Aquaponics</h1>\n"
"      <h2>Sponsored by UniTan Aquafarms</h2>\n"
"      <canvas id=\"tempChart\" width=\"1600\" height=\"900\"></canvas>\n"
"      <canvas id=\"levelChart\" width=\"1600\" height=\"900\"></canvas>\n"
"      <canvas id=\"powerChart\" width=\"1600\" height=\"900\"></canvas>\n"
"      <canvas id=\"lightChart\" width=\"1600\" height=\"900\"></canvas>\n"
"    </div>\n"
"\n"
"    <script src=\"script.js\"></script>\n"
"  </body>\n"
"</html>\n";
