const char jsString[] = "// Our labels along the x-axis\n"
"//var years = [1500,1600,1700,1750,1800,1850,1900,1950,1999,2050];\n"
"var time = [12,1,2,3,4,5,6,7,8,9];\n"
"// For drawing the lines\n"
"var temp = [20,30,40,50,60,70,80,75,80,70];\n\n"
"var level = [50,60,50,40,50,60,50,40,50,60];\n"
"var power = [5,6,5,4,5,6,5,4,5,6];\n"
"var light = [0.5,0.5,0.5,1.5,1.5,1.5,0.5,0.5,1.5,1.5];\n"
"var northAmerica = [6,3,2,2,7,26,82,172,312,433];\n"
"\n"
"var ctx = document.getElementById(\"tempChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time,\n"
"    datasets: [\n"
"      {"
"        data: temp,"
"        label: \"Temperature\",\n"
"        borderColor: \"#FFC12B\",\n"
"		fill: false\n"
"      }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"var ctx = document.getElementById(\"levelChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time,\n"
"    datasets: [\n"
"	  {"
"   		data: level,\n"
"   		label: \"Water Level\",\n"
"   		borderColor: \"#9F3BFF\",\n"
"   		fill: false\n"
" 	  }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"var ctx = document.getElementById(\"powerChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time,\n"
"    datasets: [\n"
"    {\n"
"      data: power,\n"
"      label: \"Power Consumption\",\n"
"      borderColor: \"#37B0FF\",\n"
"      fill: false\n"
"    }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"var ctx = document.getElementById(\"lightChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time,\n"
"    datasets: [\n"
"    {\n"
"      data: light,\n"
"      label: \"Lighting power Consumption\",\n"
"      borderColor: \"#FF2B30\",\n"
"      fill: false\n"
"    }\n"
"    ]\n"
"  }\n"
"});\n";
