const char jsString[] = ""
"// Our labels along the x-axis\n"
"var time = \"1,2,3,4,5,6,7,8,9,10,11,12\";\n"
"// For drawing the lines\n"
"var temp = \"20,30,40,50,60,70,80,75,80,70\";\n"
"var level = \"50,60,50,40,50,60,50,40,50,60\";\n"
"var power = \"5,6,5,4,5,6,5,4,5,6\";\n"
"var light = \"0.5,0.5,0.5,1.5,1.5,1.5,0.5,0.5,1.5,1.5\";\n"
"\n"
"// temperature chart\n"
"var ctx = document.getElementById(\"tempChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time.split(','),\n"
"    datasets: [\n"
"      { \n"
"        data: temp.split(','),\n"
"//        data: \%TEMPERATURE\%.split(','),\n"
"        label: \"Temperature\",\n"
"        borderColor: \"#FFC12B\",\n"
"        fill: false\n"
"      }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"// water level chart\n"
"var ctx = document.getElementById(\"levelChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time.split(','),\n"
"    datasets: [\n"
"    { \n"
"      data: level.split(','),\n"
"//      data: \%LEVEL\%.split(','),\n"
"      label: \"Water Level\",\n"
"      borderColor: \"#9F3BFF\",\n"
"      fill: false\n"
"    }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"// Power chart\n"
"var ctx = document.getElementById(\"powerChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time.split(','),\n"
"    datasets: [\n"
"    { \n"
"      data: power.split(','),\n"
"//      data: \%POWER\%.split(','),\n"
"      label: \"Power Consumption\",\n"
"      borderColor: \"#37B0FF\",\n"
"      fill: false\n"
"    }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"// light power chart\n"
"var ctx = document.getElementById(\"lightChart\");\n"
"var myChart = new Chart(ctx, {\n"
"  type: 'line',\n"
"  data: {\n"
"    labels: time.split(','),\n"
"    datasets: [\n"
"    { \n"
"       data: light.split(','),\n"
"//     data: \%LIGHT\%.split(','),\n"
"      label: \"Lighting power Consumption\",\n"
"      borderColor: \"#FF2B30\",\n"
"      fill: false\n"
"    }\n"
"    ]\n"
"  }\n"
"});\n"
"\n"
"// update interval\n"
"setInterval(function ( ) {\n"
"  var xhttp = new XMLHttpRequest();\n"
"  xhttp.onreadystatechange = function() {\n"
"    if (this.readyState == 4 && this.status == 200) {\n"
"      document.getElementById(\"temp\").innerHTML = this.responseText;\n"
"    }\n"
"  };\n"
"  xhttp.open(\"GET\", \"/temp\", true);\n"
"  xhttp.send();\n"
"}, 60000 ) ; // repeat once a minute\n"
"\n"
"setInterval(function ( ) {\n"
"  var xhttp = new XMLHttpRequest();\n"
"  xhttp.onreadystatechange = function() {\n"
"    if (this.readyState == 4 && this.status == 200) {\n"
"      document.getElementById(\"level\").innerHTML = this.responseText;\n"
"    }\n"
"  };\n"
"  xhttp.open(\"GET\", \"/level\", true);\n"
"  xhttp.send();\n"
"}, 60000 ) ; // repeat once a minute\n"
"\n"
"setInterval(function ( ) {\n"
"  var xhttp = new XMLHttpRequest();\n"
"  xhttp.onreadystatechange = function() {\n"
"    if (this.readyState == 4 && this.status == 200) {\n"
"      document.getElementById(\"power\").innerHTML = this.responseText;\n"
"    }\n"
"  };\n"
"  xhttp.open(\"GET\", \"/power\", true);\n"
"  xhttp.send();\n"
"}, 60000 ) ; // repeat once a minute\n"
"\n"
"setInterval(function ( ) {\n"
"  var xhttp = new XMLHttpRequest();\n"
"  xhttp.onreadystatechange = function() {\n"
"    if (this.readyState == 4 && this.status == 200) {\n"
"      document.getElementById(light).innerHTML = this.responseText;\n"
"    }\n"
"  };\n"
"  xhttp.open(\"GET\", \"/light\", true);\n"
"  xhttp.send();\n"
"}, 60000 ) ; // repeat once a minute\n";
